version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      SPRING_DEVTOOLS_ENABLED: true
      SPRING_DEVTOOLS_LIVE_RELOAD_ENABLED: true
    ports:
      - "${PRODUCT_SERVICE_PORT}:8080"
    volumes:
      - ./product-service:/app
      - ~/.m2:/app/.m2
    depends_on:
      - postgres
volumes:
  postgres_data: